//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.27 at 02:55:26 PM IST 
//


package com.customparser.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.medline package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.medline
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HealthTopics }
     * 
     */
    public HealthTopics createHealthTopics() {
        return new HealthTopics();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic }
     * 
     */
    public HealthTopics.HealthTopic createHealthTopicsHealthTopic() {
        return new HealthTopics.HealthTopic();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.MeshHeading }
     * 
     */
    public HealthTopics.HealthTopic.MeshHeading createHealthTopicsHealthTopicMeshHeading() {
        return new HealthTopics.HealthTopic.MeshHeading();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.Group }
     * 
     */
    public HealthTopics.HealthTopic.Group createHealthTopicsHealthTopicGroup() {
        return new HealthTopics.HealthTopic.Group();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.LanguageMappedTopic }
     * 
     */
    public HealthTopics.HealthTopic.LanguageMappedTopic createHealthTopicsHealthTopicLanguageMappedTopic() {
        return new HealthTopics.HealthTopic.LanguageMappedTopic();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.OtherLanguage }
     * 
     */
    public HealthTopics.HealthTopic.OtherLanguage createHealthTopicsHealthTopicOtherLanguage() {
        return new HealthTopics.HealthTopic.OtherLanguage();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.PrimaryInstitute }
     * 
     */
    public HealthTopics.HealthTopic.PrimaryInstitute createHealthTopicsHealthTopicPrimaryInstitute() {
        return new HealthTopics.HealthTopic.PrimaryInstitute();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.RelatedTopic }
     * 
     */
    public HealthTopics.HealthTopic.RelatedTopic createHealthTopicsHealthTopicRelatedTopic() {
        return new HealthTopics.HealthTopic.RelatedTopic();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.MeshHeading.Descriptor }
     * 
     */
    public HealthTopics.HealthTopic.MeshHeading.Descriptor createHealthTopicsHealthTopicMeshHeadingDescriptor() {
        return new HealthTopics.HealthTopic.MeshHeading.Descriptor();
    }

    /**
     * Create an instance of {@link HealthTopics.HealthTopic.MeshHeading.Qualifier }
     * 
     */
    public HealthTopics.HealthTopic.MeshHeading.Qualifier createHealthTopicsHealthTopicMeshHeadingQualifier() {
        return new HealthTopics.HealthTopic.MeshHeading.Qualifier();
    }

}
