/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.customparser.avro;  
@SuppressWarnings("all")
public class HealthTopicsHealthTopicGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"HealthTopicsHealthTopicGroup\",\"namespace\":\"com.medline.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"url\",\"type\":[\"null\",\"string\"],\"default\":\"null\"},{\"name\":\"id\",\"type\":[\"null\",\"int\"],\"default\":\"null\"}]}");
  public java.lang.CharSequence value;
  public java.lang.CharSequence url;
  public java.lang.Integer id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    case 1: return url;
    case 2: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    case 1: url = (java.lang.CharSequence)value$; break;
    case 2: id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
